### ISSUE TITLE
Touch Agromelio

### ISSUE THREAD

**Issue by asavershin** [AgroScience-Team/artefacts#16]
1. Посмотреть функционал сайта
    * Какие плюсы и минусы?
    * Выяснить какие технологии использовались(ВКР в помощь)
1. Reverse engineering
    * Постараться используя ВКР и сайт составить предполагаемое ТЗ
1. Сделать презентацию или текстовый документ с краткой выжимкой, чтобы другие участники разобрались. Всё делать в формате PDF.
Deadline 04.10.23 17:59

P.S.
ВКР в первую очередь.

UPD: Deadline 17.00 @NadyaPronina

**Comment by 1ordhokage** [comment]
@NadyaPronina что тут надо ревьюить?
