### ISSUE TITLE
Google Earth engine

### ISSUE THREAD

**Issue by 1ordhokage** [AgroScience-Team/artefacts#18]
1. Посмотреть функционал сервиса
2. Выяснить, возможна ли интеграция функционала сервиса с Цифровым двойником (API).
3. Сделать презентацию или текстовый документ с краткой выжимкой, чтобы другие участники разобрались. Всё делать в формате PDF.

Deadline 04.10.23 17:59

**Comment by Abobus1k** [comment]
В нашем случае мы не можем пользоваться таким сервисом как Google Earth engine
