### ISSUE TITLE
fields service contract

### ISSUE THREAD

**Issue by 1ordhokage** [AgroScience-Team/artefacts#37]
Спроектировать контракт для API сервиса полей.

**Comment by Abobus1k** [comment]
**Requests:**

**GET** `api/v1/fields/?organization_id=&&page=`

**Response:**

- 200, 401, 404, 500

```
`{
	{     
	name,
	square_area,    
	geom,
	description,
	color,
	activity_start,     
	activity_end,
	},   
	...
}`
```

**POST** `api/v1/fields`

```
`{
	{     
	name,
	square_area,    
	geom,
	description,
	color,
	activity_start,     
	activity_end,
	}
}`
```

**Response:**

- 201, 400, 401, 403, 404, 500

**GET** `api/v1/fields/{field_id}`

**Response:**

- 200, 401, 404, 500

```
`{
	{     
	organization_name,
	field_name,    
	square_area,
	activity_start,
	activity_end,
	description,     
	{
	crop_name,
	crop-rotation_start_time,
	crop-rotation_end_time,
	crop-rotation_descrition
	}
	},   
	...
}`
```

**DELETE** `api/v1/fields/{field_id}`

**Response:**

- 201, 400, 401, 403, 404, 500

**GET** `api/v1/fields/preview`

**Response:**

- 200, 401, 404, 500


```
`{
	{     
	field_name,
	crop_name,    
	color,
	geom,
	},
	...
}`
```


**GET** `api/v1/fields/preview/{field_id}`

**Response:**

- 200, 401, 404, 500


```
`{
	{     
	field_name,
	crop_name,    
	color,
	geom,
	}
}`
```

**PUT** `api/v1/fields/{field_id}`


`{   name,   square_area,   geom,   description,   activity_start,   activity_end,   color }`
```
`{
	{     
	name,
	square_area,    
	geom,
	description,
	activity_start,
	activity_end,     
	color
	}
}`
```

**Response:**

- 201, 400, 401, 403, 404, 500

**Comment by 1ordhokage** [comment]
1) "GET api/v1/fields/?organization_id=&&page="  -  пока пагинация не нужна
2) где аэрофотосники?
